//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 01:53:04 PM CEST 
//


package com.github.shell88.bddvideoannotator.annotationfile.exporter.eaf;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for cventryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cventryType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EXT_REF" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cventryType", propOrder = {
    "value"
})
@XmlSeeAlso({
    EcvEntryType.class
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
public class CventryType {

    @XmlValue
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected String value;
    @XmlAttribute(name = "DESCRIPTION")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected String description;
    @XmlAttribute(name = "EXT_REF")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected Object extref;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the extref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public Object getEXTREF() {
        return extref;
    }

    /**
     * Sets the value of the extref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setEXTREF(Object value) {
        this.extref = value;
    }

}
