//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 01:53:04 PM CEST 
//


package com.github.shell88.bddvideoannotator.annotationfile.exporter.eaf;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CONTROLLED_VOCABULARY" type="{}ecvConvocType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="EXTERNAL_REF" type="{}extRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="AUTHOR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="VERSION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "controlledvocabulary",
    "externalref"
})
@XmlRootElement(name = "CV_RESOURCE")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
public class CVRESOURCE {

    @XmlElement(name = "CONTROLLED_VOCABULARY", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected List<EcvConvocType> controlledvocabulary;
    @XmlElement(name = "EXTERNAL_REF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected List<ExtRefType> externalref;
    @XmlAttribute(name = "DATE")
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "AUTHOR")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected String author;
    @XmlAttribute(name = "VERSION")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected String version;

    /**
     * Gets the value of the controlledvocabulary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlledvocabulary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONTROLLEDVOCABULARY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EcvConvocType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public List<EcvConvocType> getCONTROLLEDVOCABULARY() {
        if (controlledvocabulary == null) {
            controlledvocabulary = new ArrayList<EcvConvocType>();
        }
        return this.controlledvocabulary;
    }

    /**
     * Gets the value of the externalref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXTERNALREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtRefType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public List<ExtRefType> getEXTERNALREF() {
        if (externalref == null) {
            externalref = new ArrayList<ExtRefType>();
        }
        return this.externalref;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public XMLGregorianCalendar getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setDATE(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public String getAUTHOR() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setAUTHOR(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setVERSION(String value) {
        this.version = value;
    }

}
