//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 01:53:04 PM CEST 
//


package com.github.shell88.bddvideoannotator.annotationfile.exporter.eaf;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for extRefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="extRefType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="EXT_REF_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="TYPE" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="iso12620"/&gt;
 *             &lt;enumeration value="ecv"/&gt;
 *             &lt;enumeration value="cve_id"/&gt;
 *             &lt;enumeration value="lexen_id"/&gt;
 *             &lt;enumeration value="resource_url"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="VALUE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "extRefType")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
public class ExtRefType {

    @XmlAttribute(name = "EXT_REF_ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected String extrefid;
    @XmlAttribute(name = "TYPE", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected String type;
    @XmlAttribute(name = "VALUE", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected String value;

    /**
     * Gets the value of the extrefid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public String getEXTREFID() {
        return extrefid;
    }

    /**
     * Sets the value of the extrefid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setEXTREFID(String value) {
        this.extrefid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public String getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setTYPE(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public String getVALUE() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setVALUE(String value) {
        this.value = value;
    }

}
