//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 01:53:04 PM CEST 
//


package com.github.shell88.bddvideoannotator.annotationfile.exporter.eaf;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for refAnnoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="refAnnoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ANNOTATION_VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{}annotationAttribute"/&gt;
 *       &lt;attribute name="ANNOTATION_REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="PREVIOUS_ANNOTATION" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "refAnnoType", propOrder = {
    "annotationvalue"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
public class RefAnnoType {

    @XmlElement(name = "ANNOTATION_VALUE", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected String annotationvalue;
    @XmlAttribute(name = "ANNOTATION_REF", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected Object annotationref;
    @XmlAttribute(name = "PREVIOUS_ANNOTATION")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected Object previousannotation;
    @XmlAttribute(name = "ANNOTATION_ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected String annotationid;
    @XmlAttribute(name = "EXT_REF")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    protected List<Object> extref;

    /**
     * Gets the value of the annotationvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public String getANNOTATIONVALUE() {
        return annotationvalue;
    }

    /**
     * Sets the value of the annotationvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setANNOTATIONVALUE(String value) {
        this.annotationvalue = value;
    }

    /**
     * Gets the value of the annotationref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public Object getANNOTATIONREF() {
        return annotationref;
    }

    /**
     * Sets the value of the annotationref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setANNOTATIONREF(Object value) {
        this.annotationref = value;
    }

    /**
     * Gets the value of the previousannotation property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public Object getPREVIOUSANNOTATION() {
        return previousannotation;
    }

    /**
     * Sets the value of the previousannotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setPREVIOUSANNOTATION(Object value) {
        this.previousannotation = value;
    }

    /**
     * Gets the value of the annotationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public String getANNOTATIONID() {
        return annotationid;
    }

    /**
     * Sets the value of the annotationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public void setANNOTATIONID(String value) {
        this.annotationid = value;
    }

    /**
     * Gets the value of the extref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXTREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-17T01:53:04+02:00", comments = "JAXB RI v2.2.11")
    public List<Object> getEXTREF() {
        if (extref == null) {
            extref = new ArrayList<Object>();
        }
        return this.extref;
    }

}
