
package com.github.shell88.bddvideoannotator.stubjava;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnnotationServiceService", targetNamespace = "http://service.bddvideoannotator.shell88.github.com/", wsdlLocation = "file:/C:/Users/Hell/workspace_videoannotator/java-adapter/target/wsdl/META-INF/wsdl/AnnotationServiceService.wsdl")
public class AnnotationServiceService
    extends Service
{

    private final static URL ANNOTATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ANNOTATIONSERVICESERVICE_EXCEPTION;
    private final static QName ANNOTATIONSERVICESERVICE_QNAME = new QName("http://service.bddvideoannotator.shell88.github.com/", "AnnotationServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Hell/workspace_videoannotator/java-adapter/target/wsdl/META-INF/wsdl/AnnotationServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANNOTATIONSERVICESERVICE_WSDL_LOCATION = url;
        ANNOTATIONSERVICESERVICE_EXCEPTION = e;
    }

    public AnnotationServiceService() {
        super(__getWsdlLocation(), ANNOTATIONSERVICESERVICE_QNAME);
    }

    public AnnotationServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANNOTATIONSERVICESERVICE_QNAME, features);
    }

    public AnnotationServiceService(URL wsdlLocation) {
        super(wsdlLocation, ANNOTATIONSERVICESERVICE_QNAME);
    }

    public AnnotationServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANNOTATIONSERVICESERVICE_QNAME, features);
    }

    public AnnotationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnnotationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnnotationService
     */
    @WebEndpoint(name = "AnnotationServicePort")
    public AnnotationService getAnnotationServicePort() {
        return super.getPort(new QName("http://service.bddvideoannotator.shell88.github.com/", "AnnotationServicePort"), AnnotationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnnotationService
     */
    @WebEndpoint(name = "AnnotationServicePort")
    public AnnotationService getAnnotationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bddvideoannotator.shell88.github.com/", "AnnotationServicePort"), AnnotationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANNOTATIONSERVICESERVICE_EXCEPTION!= null) {
            throw ANNOTATIONSERVICESERVICE_EXCEPTION;
        }
        return ANNOTATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
