//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 10:43:14 AM CEST 
//


package com.github.shell88.bddvideoannotator.eaf;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for alignableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="alignableType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ANNOTATION_VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{}annotationAttribute"/&gt;
 *       &lt;attribute name="TIME_SLOT_REF1" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="TIME_SLOT_REF2" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="SVG_REF" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alignableType", propOrder = {
    "annotationvalue"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
public class AlignableType {

    @XmlElement(name = "ANNOTATION_VALUE", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected String annotationvalue;
    @XmlAttribute(name = "TIME_SLOT_REF1", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected Object timeslotref1;
    @XmlAttribute(name = "TIME_SLOT_REF2", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected Object timeslotref2;
    @XmlAttribute(name = "SVG_REF")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected Object svgref;
    @XmlAttribute(name = "ANNOTATION_ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected String annotationid;

    /**
     * Gets the value of the annotationvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public String getANNOTATIONVALUE() {
        return annotationvalue;
    }

    /**
     * Sets the value of the annotationvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setANNOTATIONVALUE(String value) {
        this.annotationvalue = value;
    }

    /**
     * Gets the value of the timeslotref1 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public Object getTIMESLOTREF1() {
        return timeslotref1;
    }

    /**
     * Sets the value of the timeslotref1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setTIMESLOTREF1(Object value) {
        this.timeslotref1 = value;
    }

    /**
     * Gets the value of the timeslotref2 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public Object getTIMESLOTREF2() {
        return timeslotref2;
    }

    /**
     * Sets the value of the timeslotref2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setTIMESLOTREF2(Object value) {
        this.timeslotref2 = value;
    }

    /**
     * Gets the value of the svgref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public Object getSVGREF() {
        return svgref;
    }

    /**
     * Sets the value of the svgref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setSVGREF(Object value) {
        this.svgref = value;
    }

    /**
     * Gets the value of the annotationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public String getANNOTATIONID() {
        return annotationid;
    }

    /**
     * Sets the value of the annotationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setANNOTATIONID(String value) {
        this.annotationid = value;
    }

}
