//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 10:43:14 AM CEST 
//


package com.github.shell88.bddvideoannotator.eaf;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for annotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="annotationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="ALIGNABLE_ANNOTATION" type="{}alignableType"/&gt;
 *         &lt;element name="REF_ANNOTATION" type="{}refAnnoType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "annotationType", propOrder = {
    "alignableannotation",
    "refannotation"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
public class AnnotationType {

    @XmlElement(name = "ALIGNABLE_ANNOTATION")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected AlignableType alignableannotation;
    @XmlElement(name = "REF_ANNOTATION")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected RefAnnoType refannotation;

    /**
     * Gets the value of the alignableannotation property.
     * 
     * @return
     *     possible object is
     *     {@link AlignableType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public AlignableType getALIGNABLEANNOTATION() {
        return alignableannotation;
    }

    /**
     * Sets the value of the alignableannotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlignableType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setALIGNABLEANNOTATION(AlignableType value) {
        this.alignableannotation = value;
    }

    /**
     * Gets the value of the refannotation property.
     * 
     * @return
     *     possible object is
     *     {@link RefAnnoType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public RefAnnoType getREFANNOTATION() {
        return refannotation;
    }

    /**
     * Sets the value of the refannotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefAnnoType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setREFANNOTATION(RefAnnoType value) {
        this.refannotation = value;
    }

}
