//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 10:43:14 AM CEST 
//


package com.github.shell88.bddvideoannotator.eaf;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for lingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="LINGUISTIC_TYPE_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="TIME_ALIGNABLE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CONSTRAINTS" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="GRAPHIC_REFERENCES" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CONTROLLED_VOCABULARY_REF" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lingType")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
public class LingType {

    @XmlAttribute(name = "LINGUISTIC_TYPE_ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected String linguistictypeid;
    @XmlAttribute(name = "TIME_ALIGNABLE")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected String timealignable;
    @XmlAttribute(name = "CONSTRAINTS")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected Object constraints;
    @XmlAttribute(name = "GRAPHIC_REFERENCES")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected String graphicreferences;
    @XmlAttribute(name = "CONTROLLED_VOCABULARY_REF")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected Object controlledvocabularyref;

    /**
     * Gets the value of the linguistictypeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public String getLINGUISTICTYPEID() {
        return linguistictypeid;
    }

    /**
     * Sets the value of the linguistictypeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setLINGUISTICTYPEID(String value) {
        this.linguistictypeid = value;
    }

    /**
     * Gets the value of the timealignable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public String getTIMEALIGNABLE() {
        return timealignable;
    }

    /**
     * Sets the value of the timealignable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setTIMEALIGNABLE(String value) {
        this.timealignable = value;
    }

    /**
     * Gets the value of the constraints property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public Object getCONSTRAINTS() {
        return constraints;
    }

    /**
     * Sets the value of the constraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setCONSTRAINTS(Object value) {
        this.constraints = value;
    }

    /**
     * Gets the value of the graphicreferences property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public String getGRAPHICREFERENCES() {
        return graphicreferences;
    }

    /**
     * Sets the value of the graphicreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setGRAPHICREFERENCES(String value) {
        this.graphicreferences = value;
    }

    /**
     * Gets the value of the controlledvocabularyref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public Object getCONTROLLEDVOCABULARYREF() {
        return controlledvocabularyref;
    }

    /**
     * Sets the value of the controlledvocabularyref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setCONTROLLEDVOCABULARYREF(Object value) {
        this.controlledvocabularyref = value;
    }

}
