//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 10:43:14 AM CEST 
//


package com.github.shell88.bddvideoannotator.eaf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.shell88.bddvideoannotator.eaf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.shell88.bddvideoannotator.eaf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link ANNOTATIONDOCUMENT }
     * 
     */
    public ANNOTATIONDOCUMENT createANNOTATIONDOCUMENT() {
        return new ANNOTATIONDOCUMENT();
    }

    /**
     * Create an instance of {@link TierType }
     * 
     */
    public TierType createTierType() {
        return new TierType();
    }

    /**
     * Create an instance of {@link LingType }
     * 
     */
    public LingType createLingType() {
        return new LingType();
    }

    /**
     * Create an instance of {@link LocaleType }
     * 
     */
    public LocaleType createLocaleType() {
        return new LocaleType();
    }

    /**
     * Create an instance of {@link ConstraintType }
     * 
     */
    public ConstraintType createConstraintType() {
        return new ConstraintType();
    }

    /**
     * Create an instance of {@link ConvocType }
     * 
     */
    public ConvocType createConvocType() {
        return new ConvocType();
    }

    /**
     * Create an instance of {@link AnnotationType }
     * 
     */
    public AnnotationType createAnnotationType() {
        return new AnnotationType();
    }

    /**
     * Create an instance of {@link AlignableType }
     * 
     */
    public AlignableType createAlignableType() {
        return new AlignableType();
    }

    /**
     * Create an instance of {@link RefAnnoType }
     * 
     */
    public RefAnnoType createRefAnnoType() {
        return new RefAnnoType();
    }

    /**
     * Create an instance of {@link CventryType }
     * 
     */
    public CventryType createCventryType() {
        return new CventryType();
    }

    /**
     * Create an instance of {@link TimeType.TIMESLOT }
     * 
     */
    public TimeType.TIMESLOT createTimeTypeTIMESLOT() {
        return new TimeType.TIMESLOT();
    }

    /**
     * Create an instance of {@link HeadType.MEDIADESCRIPTOR }
     * 
     */
    public HeadType.MEDIADESCRIPTOR createHeadTypeMEDIADESCRIPTOR() {
        return new HeadType.MEDIADESCRIPTOR();
    }

    /**
     * Create an instance of {@link HeadType.LINKEDFILEDESCRIPTOR }
     * 
     */
    public HeadType.LINKEDFILEDESCRIPTOR createHeadTypeLINKEDFILEDESCRIPTOR() {
        return new HeadType.LINKEDFILEDESCRIPTOR();
    }

}
