//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 10:43:14 AM CEST 
//


package com.github.shell88.bddvideoannotator.eaf;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tierType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ANNOTATION" type="{}annotationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="TIER_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="PARTICIPANT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LINGUISTIC_TYPE_REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="DEFAULT_LOCALE" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="PARENT_REF" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tierType", propOrder = {
    "annotation"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
public class TierType {

    @XmlElement(name = "ANNOTATION")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected List<AnnotationType> annotation;
    @XmlAttribute(name = "TIER_ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected String tierid;
    @XmlAttribute(name = "PARTICIPANT")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected String participant;
    @XmlAttribute(name = "LINGUISTIC_TYPE_REF", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected Object linguistictyperef;
    @XmlAttribute(name = "DEFAULT_LOCALE")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected Object defaultlocale;
    @XmlAttribute(name = "PARENT_REF")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected Object parentref;

    /**
     * Gets the value of the annotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getANNOTATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotationType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public List<AnnotationType> getANNOTATION() {
        if (annotation == null) {
            annotation = new ArrayList<AnnotationType>();
        }
        return this.annotation;
    }

    /**
     * Gets the value of the tierid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public String getTIERID() {
        return tierid;
    }

    /**
     * Sets the value of the tierid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setTIERID(String value) {
        this.tierid = value;
    }

    /**
     * Gets the value of the participant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public String getPARTICIPANT() {
        return participant;
    }

    /**
     * Sets the value of the participant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setPARTICIPANT(String value) {
        this.participant = value;
    }

    /**
     * Gets the value of the linguistictyperef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public Object getLINGUISTICTYPEREF() {
        return linguistictyperef;
    }

    /**
     * Sets the value of the linguistictyperef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setLINGUISTICTYPEREF(Object value) {
        this.linguistictyperef = value;
    }

    /**
     * Gets the value of the defaultlocale property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public Object getDEFAULTLOCALE() {
        return defaultlocale;
    }

    /**
     * Sets the value of the defaultlocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setDEFAULTLOCALE(Object value) {
        this.defaultlocale = value;
    }

    /**
     * Gets the value of the parentref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public Object getPARENTREF() {
        return parentref;
    }

    /**
     * Sets the value of the parentref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public void setPARENTREF(Object value) {
        this.parentref = value;
    }

}
