//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 10:43:14 AM CEST 
//


package com.github.shell88.bddvideoannotator.eaf;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for timeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="timeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TIME_SLOT" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="TIME_SLOT_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *                 &lt;attribute name="TIME_VALUE" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timeType", propOrder = {
    "timeslot"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
public class TimeType {

    @XmlElement(name = "TIME_SLOT")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    protected List<TimeType.TIMESLOT> timeslot;

    /**
     * Gets the value of the timeslot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeslot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTIMESLOT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeType.TIMESLOT }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public List<TimeType.TIMESLOT> getTIMESLOT() {
        if (timeslot == null) {
            timeslot = new ArrayList<TimeType.TIMESLOT>();
        }
        return this.timeslot;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="TIME_SLOT_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
     *       &lt;attribute name="TIME_VALUE" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
    public static class TIMESLOT {

        @XmlAttribute(name = "TIME_SLOT_ID", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
        protected String timeslotid;
        @XmlAttribute(name = "TIME_VALUE")
        @XmlSchemaType(name = "unsignedInt")
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
        protected Long timevalue;

        /**
         * Gets the value of the timeslotid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
        public String getTIMESLOTID() {
            return timeslotid;
        }

        /**
         * Sets the value of the timeslotid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
        public void setTIMESLOTID(String value) {
            this.timeslotid = value;
        }

        /**
         * Gets the value of the timevalue property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
        public Long getTIMEVALUE() {
            return timevalue;
        }

        /**
         * Sets the value of the timevalue property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-06-15T10:43:14+02:00", comments = "JAXB RI v2.2.11")
        public void setTIMEVALUE(Long value) {
            this.timevalue = value;
        }

    }

}
